### ISSUE TITLE
i-bem, i-bem-dom: document new api

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-core#578]
- [x] `i-bem__dom` -> `i-bem-dom` #413
- [x] `decl*`
- [x] `onSetMod` #1072 #1025
- [x] `live` -> `lazyInit`+`onInit` #877
- [x] elems as first-class instances #581
- [x] `find*`, `containsDomElem` -> `containsBemEntity`
- [x] collections #582
- [x] events #394
- [x] `_` for `@protected` #586
- [x] `_dropElemCache`
